spring.application.name=webapp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/springdb
spring.datasource.username=sptinguser
spring.datasource.password=springpass
spring.sql.init.mode=always
logging.level.com.example.webapp.repository=DEBUG
